#!/usr/scripts/env python

from distutils.core import setup

NAME = "m4db_serverside"
VERSION = "1.0.0"

setup(name=NAME,
      version=VERSION,
      license="MIT",
      description="M4DB server side utiltiles",
      url="https://bitbucket.org/micromag/{name:}/src/master/".format(name=NAME),
      download_url="https://bitbucket.org/micromag/{name:}/get/{name:}-{version:}.zip".format(name=NAME, version=VERSION),
      keywords=["micromagnetics", "database"],
      author="L. Nagy, W. Williams",
      author_email="lnagy2@ed.ac.uk",
      packages=["m4db_serverside",
                "m4db_serverside.db",
                "m4db_serverside.db.db_user",
                "m4db_serverside.db.external_field",
                "m4db_serverside.db.geometry",
                "m4db_serverside.db.initial_magnetization",
                "m4db_serverside.db.model",
                "m4db_serverside.db.model_material_associations",
                "m4db_serverside.db.model_materials_text",
                "m4db_serverside.db.project",
                "m4db_serverside.db.running_status",
                "m4db_serverside.db.size_convention",
                "m4db_serverside.db.software",
                "m4db_serverside.db.unit",
                "m4db_serverside.db",
                "m4db_serverside.file_io",
                "m4db_serverside.parsers",
                "m4db_serverside.postprocessing",
                "m4db_serverside.script_gen",
                "m4db_serverside.scripts",
                "m4db_serverside.scripts.m4db_create_config",
                "m4db_serverside.scripts.m4db_geometry",
                "m4db_serverside.scripts.m4db_model",
                "m4db_serverside.scripts.m4db_project",
                "m4db_serverside.scripts.m4db_software",
                "m4db_serverside.scripts.m4db_user",
                "m4db_serverside.templates",
                "m4db_serverside.templates.merrill",
                "m4db_serverside.templates.slurm",
                "m4db_serverside.utilities"],
      package_dir={"m4db_serverside": "lib/m4db_serverside",
                   "m4db_serverside.db": "lib/m4db_serverside/db",
                   "m4db_serverside.db.db_user": "lib/m4db_serverside/db/db_user",
                   "m4db_serverside.db.external_field": "lib/m4db_serverside/db/external_field",
                   "m4db_serverside.db.geometry": "lib/m4db_serverside/db/geometry",
                   "m4db_serverside.db.initial_magnetization": "lib/m4db_serverside/db/initial_magnetization",
                   "m4db_serverside.db.model": "lib/m4db_serverside/db/model",
                   "m4db_serverside.db.model_material_associations": "lib/m4db_serverside/db/model_material_associations",
                   "m4db_serverside.db.model_materials_text": "lib/m4db_serverside/db/model_materials_text",
                   "m4db_serverside.db.project": "lib/m4db_serverside/db/project",
                   "m4db_serverside.db.running_status": "lib/m4db_serverside/db/running_status",
                   "m4db_serverside.db.size_convention": "lib/m4db_serverside/db/size_convention",
                   "m4db_serverside.db.software": "lib/m4db_serverside/db/software",
                   "m4db_serverside.db.unit": "lib/m4db_serverside/db/unit",
                   "m4db_serverside.file_io": "lib/m4db_serverside/file_io",
                   "m4db_serverside.parsers": "lib/m4db_serverside/parsers",
                   "m4db_serverside.postprocessing": "lib/m4db_serverside/postprocessing",
                   "m4db_serverside.script_gen": "lib/m4db_serverside/script_gen",
                   "m4db_serverside.scripts": "lib/m4db_serverside/scripts",
                   "m4db_serverside.scripts.m4db_create_config": "lib/m4db_serverside/scripts/m4db_create_config",
                   "m4db_serverside.scripts.m4db_geometry": "lib/m4db_serverside/scripts/m4db_geometry",
                   "m4db_serverside.scripts.m4db_model": "lib/m4db_serverside/scripts/m4db_model",
                   "m4db_serverside.scripts.m4db_project": "lib/m4db_serverside/scripts/m4db_project",
                   "m4db_serverside.scripts.m4db_software": "lib/m4db_serverside/scripts/m4db_software",
                   "m4db_serverside.scripts.m4db_user": "lib/m4db_serverside/scripts/m4db_user",
                   "m4db_serverside.templates": "lib/m4db_serverside/templates",
                   "m4db_serverside.templates.merrill": "lib/m4db_serverside/templates/merrill",
                   "m4db_serverside.templates.slurm": "lib/m4db_serverside/templates/slurm",
                   "m4db_serverside.utilities": "lib/m4db_serverside/utilities"},
      scripts=[
              "scripts/m4db_create_config",
              "scripts/m4db_geometry",
              "scripts/m4db_model",
              "scripts/m4db_project",
              "scripts/m4db_run_model",
              "scripts/m4db_schedule_model",
              "scripts/m4db_software",
              "scripts/m4db_user"
      ],
      classifiers=[
            "Development Status :: 3 - Alpha",
            "Intended Audience :: Developers",
            "Topic :: Database",
            "License :: OSI Approved :: MIT License",
            "Programming Language :: Python :: 3",
            "Programming Language :: Python :: 3.6",
            "Programming Language :: Python :: 3.7",
            "Programming Language :: Python :: 3.8",
      ]),
