#!python

r"""
A utility to create a serverside configuration file. This file is optional, but convenient.
"""
import os.path

from m4db_serverside.scripts.m4db_create_config.command_line_parser import command_line_parser
from m4db_serverside.scripts.m4db_create_config.actions import create_new_config

from m4db_serverside import global_vars


def main():
    parser = command_line_parser()
    args = parser.parse_args()
    create_new_config(args)
    print("Created config file, make sure to add '{}={}' to your environment!".format(
        global_vars.m4db_serverside_config_environment_variable,
        os.path.realpath(args.config_file)
    ))


if __name__ == "__main__":
    main()
