#!python

import sys

from m4db_serverside.scripts.m4db_model.command_line_parser import command_line_parser
from m4db_serverside.scripts.m4db_model.actions import add_model_action

from m4db_serverside import global_vars


def main():
    parser = command_line_parser()
    args = parser.parse_args()

    # Process --db-user and --project
    if args.db_user is None:
        print("Undefined m4db user: either set 'db_user' in '{}' or use the --db-user flag.".format(
            global_vars.m4db_serverside_config_environment_variable
        ))
        sys.exit(1)
    if args.project is None:
        print("Undefined m4db project: either set 'project' in '{}' or use the --project flat.".format(
            global_vars.m4db_serverside_config_environment_variable
        ))
        sys.exit(1)

    if args.command == "add-from-json":
        try:
            unique_ids = add_model_action(args)
            print("Created {} models with ids:".format(len(unique_ids)))
            for unique_id in unique_ids:
                print(unique_id)
        except FileNotFoundError as e:
            print(str(e))
        except ValueError as e:
            print(str(e))
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
