#!python

from argparse import ArgumentParser


def command_line_parser():
    parser = ArgumentParser()

    return parser


def main():
    parser = command_line_parser()
    args = parser.parse_args()


if __name__ == "__main__":
    main()
