#!python

from m4db_serverside.scripts.m4db_run_model.command_line_parser import command_line_parser
from m4db_serverside.scripts.m4db_run_model.actions import run_model


def main():
    parser = command_line_parser()
    args = parser.parse_args()
    run_model(args)


if __name__ == "__main__":
    main()
