#!/bin/bash

# Run the service on port 8080
gunicorn --bind=0.0.0.0:8080 \
         --log-level=debug \
         --timeout=1024 \
	       --limit-request-line 0 \
	       --limit-request-fields 32768 \
	       --limit-request-field_size 0 \
         m4db_serverside.rest.m4db_readonly_web.service:app

