#!/bin/bash

# Check that M4DB_CERT_FILE and M4DB_KEY_FILE are set.
if [[ -z "${M4DB_CERT_FILE}" ]]; then
  echo "The M4DB_CERT_FILE environment variable is not set."
  exit 1
fi

if [[ -z "${M4DB_KEY_FILE}" ]]; then
  echo "The M4DB_KEY_FILE environment variable is not set."
  exit 1
fi

# Run the service on port 8081
gunicorn --bind=0.0.0.0:8081 \
         --log-level=debug \
         --certfile=${M4DB_CERT_FILE} \
         --keyfile=${M4DB_KEY_FILE} \
         --timeout=1024 \
	       --limit-request-line 0 \
	       --limit-request-fields 32768 \
	       --limit-request-field_size 0 \
         m4db_serverside.rest.m4db_runner_web.service:app
